spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=true

gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.auth.refresh-rate-ms=3600000
gestopago.service.url=https://gestopago.portalventas.net

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000